import { Inter } from "next/font/google";
import "./globals.css";
import SnackbarProvider from "./SnackbarProvider";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kardify Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <html lang="en">
      <SnackbarProvider>
        <body className={inter.className}>{children}</body>
      </SnackbarProvider>
    </html>
    </>
  );
}
